file_format: "1"
id: scylla
name: Scylla
type: shield
url: https://github.com/NeoLupatus/zmk-config
requires: [pro_micro]
features:
  - keys
  - pointer
siblings:
  - scylla_left
  - scylla_right_trackpoint